### ISSUE TITLE
The Compressed (zipped) Folder is invalid or corrupted on Linux

### ISSUE THREAD

**Issue by Panospheric** [Grandt/PHPZip#15]
Hi Asbjørn,

Thanks again in advance for your great ZipStream class. 

A client is trying to upload a .zip file, created with ZipStream v1.5, to his Linux server and every time he is trying to unzip it with the Hepsia Control Panel's FileManager it throws an error that the zip file is invalid or corrupted. The files did get extracted and the script files work fine. 

Here is a screenshot: ![unzip20131218](https://f.cloud.github.com/assets/5914266/1770078/0f2cc54a-6781-11e3-8500-88295d04e8e9.png)

I also had issues with IE Explorer on Windows XP telling me 'The Compressed (zipped) Folder is invalid or corrupted' and does not unzip the files. I can unzip it with any other utilitiy etc. TugZip, WinRar

Thank you very much for your consideration.

Best regards,

Chris

**Comment by ntshyadav57** [comment]
Hello How Can i get Hepsia control panel?
