### ISSUE TITLE
No idea how to simply load v2

### ISSUE THREAD

**Issue by sccr410** [Grandt/PHPZip#37]
v1 was really easy to include and use. With v2 I have absolutely no idea how to include the files and get started. We are having issues with users on some shared hosts with memory issues and I thought I would see if v2 worked for them. (mbstring.func_overload was not enabled on any of the servers)

**Comment by Grandt** [comment]
I've updated the readme.md to include installation steps for Composer. 

The old school was easy, however Composer does provide one excellent feature; automatic dependency control.
