### ISSUE TITLE
example?

### ISSUE THREAD

**Issue by reimax** [Grandt/PHPZip#42]
"See the examples for example usage." and no example... how to use this class?
how to save the file on disk?

**Comment by Grandt** [comment]
I though I had moved them out of the Legacy folder. 

Have a log at the example php files there while I look at getting them updated to actually use composer.json and get them moved to a new folder.

You need to add the dependency to your project's composer.json file: 
The require string is:  "phpzip/phpzip": ">=2.0.7"

In your php file, you then call the class with 

    $zip = new \PHPZip\Zip\File\Zip();
    $zip->setZipFile("ZipExample.zip"); 
    $zip->setComment("Example Zip file.");
    $zip->addFile("file data here", "file\path\and\name\inside\the\zip.file");

**Comment by reimax** [comment]
tnx, i find this, but not example how zip folders.
this class support zip folder and sub folder?

**Comment by Grandt** [comment]
PHPZip can only create zip files, not read them. 

As for sub folders, I assume you are talking about sub folders inside zip files?
Try this then: 
    $zip->addFile($data, "subdir/test/data.txt");
    $zip->addFile($data, "anothersubdir/test/data.txt");

This will create this directory structure inside the Zip file:
    \-
     |- subdir
     |   |- test
     |   |   |- data.txt
     |- anothersubdir
         |- test
             |- data.txt

**Comment by lgommans** [comment]
@Grandt:

> I though I had moved them out of the Legacy folder.

Indeed, which is why I didn't look at them before. "Legacy" sounds like it contains old stuff. Thanks for posting an example!
